### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by bezchristo** [bezchristo/unbapi#10]
Lets put it to a vote

1. 
![image](https://user-images.githubusercontent.com/1528381/112596755-e658c700-8e14-11eb-8ff4-b332f8de4faf.png)

2. 
![image](https://user-images.githubusercontent.com/1528381/112596787-f4a6e300-8e14-11eb-9f84-fca863c0381d.png)

3. 
![image](https://user-images.githubusercontent.com/1528381/112596833-02f4ff00-8e15-11eb-8455-ab40960a9d4d.png)

4.
![image](https://user-images.githubusercontent.com/1528381/112596894-1738fc00-8e15-11eb-8900-f28f8cadaf2d.png)

5.
![image](https://user-images.githubusercontent.com/1528381/112597063-4ea7a880-8e15-11eb-806c-13c655261850.png)

6.
![image](https://user-images.githubusercontent.com/1528381/112597097-5bc49780-8e15-11eb-8f6d-741b3f52adca.png)

7.
![image](https://user-images.githubusercontent.com/1528381/112597255-90385380-8e15-11eb-9007-0628cdaa4e19.png)

8. 
![image](https://user-images.githubusercontent.com/1528381/112597842-5d428f80-8e16-11eb-8067-40f004b49659.png)

9.
![image](https://user-images.githubusercontent.com/1528381/112597891-73e8e680-8e16-11eb-98d2-b1f5a9ec0ce1.png)

10. 
![image](https://user-images.githubusercontent.com/1528381/112598006-a266c180-8e16-11eb-9790-0511edd64dda.png)

11. 
![image](https://user-images.githubusercontent.com/1528381/112598083-bf02f980-8e16-11eb-97f8-99e7645710da.png)

12. 
![image](https://user-images.githubusercontent.com/1528381/112600454-e6a79100-8e19-11eb-8008-ccb839cd7bcd.png)

13. 
![image](https://user-images.githubusercontent.com/1528381/112620591-6bea7000-8e31-11eb-89ba-e07a369b28db.png)

**Comment by msomin** [comment]
Voting for `2`; easy to change colour scheme without losing the brand; seems like it will look good on paper too - in black text and white paper background.

**Comment by Janusp** [comment]
I also like 2.
